### ISSUE TITLE
gadz email - can send but cannot receive 

### ISSUE THREAD

**Issue by jcboulon** [gadzorg/gorg_mail#157]
Bonjour,

On ne peut plus recevoir d'emails - gadz.org n'est plus accessible non plus

**Comment by Issif** [comment]
Salut @jcboulon, notre hébergeur, OVH, subit de nombreuses pannes depuis 24h d'où les coupures. Le suivi de leurs incidents est sur http://travaux.ovh.net/

**Comment by jcboulon** [comment]
Salut @Issif les servers ont l'air de nouveaux opérationnels. Il y aura un nouvel envoi des emails non reçus pendant ce temps qui on été backloggés?

**Comment by Issif** [comment]
Tout dépend des émetteurs et de leurs politiques. Vue la durée, le risque de perte est très élevé.

**Comment by Issif** [comment]
L'incident étant terminé, je ferme ce ticket.
